name: build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform-version: [ 222 ]
    env:
      ORG_GRADLE_PROJECT_platformVersion: ${{ matrix.platform-version }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17

    - name: Get config
      run: |
        echo "SERVER_VERSION=${{ secrets.MINIMUNM_VERSION_REQUIREMENT }}" | sed 's/v//g' >> $GITHUB_ENV
    - name: Build
      run: |
        sed -i "s/sentryDsn=/sentryDsn=${{secrets.INTELLIJ_PLUGIN_SENTRY_DSN}}/g" src/main/resources/config.properties
        sed -i -E "s/serverVersion=(.+)/serverVersion=${{ env.SERVER_VERSION }}/g" src/main/resources/config.properties
        ./gradlew clean buildPlugin
    - uses: actions/upload-artifact@v3
      with:
        name: nocalhost-intellij-plugin-222
        path: build/distributions/
